version: "3.1"
services:
  www:
    build:
      context: ./php
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./src/:/var/www/html/
      - ./conf/httpd.conf:/etc/httpd/httpd.conf
    links:
      - db
    networks:
      - default
    depends_on:
      - db
      - composer
  db:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306::3306"
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--collation-server=utf8_general_ci',
      '--character-set-server=utf8',
    ]
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  node:
    image: "node:8.11.3"
    container_name: node
    working_dir: /home/node/app
    volumes:
      - ./src/:/home/node/app
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - ./src/:/app
volumes:
  persistent:
