version: "3.1"
services:
  www:
    build:
      context: ./php
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html/
      - ./conf/httpd.conf:/etc/httpd/httpd.conf
    links:
      - db
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306::3306"
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--collation-server=utf8_general_ci',
      '--character-set-server=utf8',
    ]
    restart: always
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app
volumes:
  persistent:
