version: "3.1"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - .:/var/www
      - ./logs:/var/log/nginx
    depends_on:
      - php
    links:
      - php
  php:
    build:
      context: ./php
    links:
      - db
    volumes:
      - .:/var/www/
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app
